[project]
name = "obscura-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "User", email = "user@example.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=3.2.4",
    "pydantic>=2.13.3",
]

[project.scripts]
obscura-mcp = "obscura_mcp:main"

[build-system]
requires = ["uv_build>=0.9.4,<0.10.0"]
build-backend = "uv_build"
